### ISSUE TITLE
pyne mesh source sampling segfaults in cases when it used to not do so

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#624]
Sometime between switching from using the `pyne-source` branch and now, pyne mesh source sampling became broken for certain problems and now segfaults. I'm not sure what broke it specifically, but my money would be on changes in the `source_sampling` routine.

**Comment by ljacobson64** [comment]
The first problem is that we updated the `source_sampling` routine to match pyne but didn't update `source.F90`. The SourceParticle constructor used to accept 5 parameters, but now accepts, 6, so when source_sampling tried to query the 6th parameter, it segfaulted. Updating `source.F90` to match pyne fixes this problem, but...

This uncovers a new problem: it has a problem in this function:

```
int pyne::Sampler::num_groups(moab::Tag tag) {
  moab::ErrorCode rval;
  int tag_size;
  rval = mesh->tag_get_bytes(tag, *(&tag_size));
  if (rval != moab::MB_SUCCESS)
    throw std::runtime_error("Problem getting tag size.");
  return tag_size / sizeof(double);
}
```

The MOAB call fails, resulting in the runtime error. Don't really know what would cause this or where to begin trying to debug it.

**Comment by zxkjack123** [comment]
I met that `runtime error` before. Because the length of `cell_fracs` is also calculated using `num_groups`. That may be cuased by  a bug in current pyne/pyne, which is fixed in this PR:https://github.com/pyne/pyne/pull/1118 (not merged yet).

**Comment by ljacobson64** [comment]
Thanks for the info Xiaokang. I will use your branch to create a new pyne.cpp/pyne.h and see if it fixes the problem.

**Comment by ljacobson64** [comment]
Hmm your branch didn't seem to fix the issue. I'm still getting
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Problem getting tag size.
```

**Comment by zxkjack123** [comment]
I updated the PR:https://github.com/pyne/pyne/pull/1118. Tested with FNG model, no runtime error found now.

**Comment by ljacobson64** [comment]
I confirmed that Xiaokang's PR (https://github.com/pyne/pyne/pull/1118) fixes this issue. Once that PR gets approved, I will submit a new PR updating amalgamated pyne (and updating source.F90 as well).

**Comment by ljacobson64** [comment]
Update: I will wait until https://github.com/pyne/pyne/pull/1139 gets approved, then I will submit a new PR here.
